#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("COP4656MusicApp.Droid.Resource", IsApplication=true)]

namespace COP4656MusicApp.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int acousticbreeze = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int back = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int happiness = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Icon = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int img_174171 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int pause_button_png_image_80706 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int play_button = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int prev_song = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int stop = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int sweet = 2130837513;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060003
			public const int artwork = 2131099651;
			
			// aapt resource value: 0x7f060002
			public const int back = 2131099650;
			
			// aapt resource value: 0x7f060000
			public const int linearLayout1 = 2131099648;
			
			// aapt resource value: 0x7f060007
			public const int nextSong = 2131099655;
			
			// aapt resource value: 0x7f060009
			public const int pause = 2131099657;
			
			// aapt resource value: 0x7f060006
			public const int play = 2131099654;
			
			// aapt resource value: 0x7f060005
			public const int prevSong = 2131099653;
			
			// aapt resource value: 0x7f060004
			public const int songTitle = 2131099652;
			
			// aapt resource value: 0x7f060001
			public const int songsList = 2131099649;
			
			// aapt resource value: 0x7f060008
			public const int stop = 2131099656;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int CustomListView = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Song = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f040000
			public const int bensound_acousticbreeze = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int bensound_happiness = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int bensound_sweet = 2130968578;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int app_name = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
